name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and Test
      run: SWIFTCHECK_MIN_SUCCESSFUL_TEST=1000 swift test -c release

